Script CleverClean.py - optimizing function code and tests
UBC-MDS/clevercloud pull request #23
Opened 2022-01-20 18:49 UTC by Arushi282

2022-01-21 08:02 UTC, adrianne-l approved these changes

2022-01-21 08:02 UTC, adrianne-l approved these changes

2022-01-22 18:08 UTC, aimee0317 requested changes

2022-01-22 18:08 UTC, aimee0317 commented on src/clevercloud/CleverClean.py
> +        Input a panda series of text / strings
```suggestion
    text : pandas.series
        Input a pandas series of text / strings
```

2022-01-22 18:13 UTC, aimee0317 approved these changes

2022-01-22 18:13 UTC, merged